// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailTicket.Models.Data;

#nullable disable

namespace RailTicket.Migrations
{
    [DbContext(typeof(RailDbContext))]
    [Migration("20231220084318_g")]
    partial class g
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailTicket.Models.Login", b =>
                {
                    b.Property<int?>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("OId"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("OId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("RailTicket.Models.Passenger", b =>
                {
                    b.Property<int?>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("PId"));

                    b.Property<long?>("Aadhar_No")
                        .HasColumnType("bigint");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Passenger_Name")
                        .HasColumnType("text");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Select_class")
                        .HasColumnType("text");

                    b.HasKey("PId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("RailTicket.Models.TicketBooking", b =>
                {
                    b.Property<int?>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("BId"));

                    b.Property<string>("From_Train")
                        .HasColumnType("text");

                    b.Property<string>("Journey_Date")
                        .HasColumnType("text");

                    b.Property<string>("To_Train")
                        .HasColumnType("text");

                    b.HasKey("BId");

                    b.ToTable("TicketBookings");
                });

            modelBuilder.Entity("RailTicket.Models.Train", b =>
                {
                    b.Property<int?>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("TId"));

                    b.Property<string>("Arrival_Time")
                        .HasColumnType("text");

                    b.Property<string>("Departure_Time")
                        .HasColumnType("text");

                    b.Property<int?>("Seat_Available")
                        .HasColumnType("integer");

                    b.Property<string>("Train_Name")
                        .HasColumnType("text");

                    b.Property<int?>("Train_No")
                        .HasColumnType("integer");

                    b.HasKey("TId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("RailTicket.Models.User_Registration", b =>
                {
                    b.Property<int?>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("RId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int?>("Pincode")
                        .HasColumnType("integer");

                    b.HasKey("RId");

                    b.ToTable("User_Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
